CREATE TABLE SESSIONS (
	ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
	USER_ID UUID REFERENCES USERS (ID) ON DELETE CASCADE,
	CREATED TIMESTAMP DEFAULT NOW(),
	EXPIRES TIMESTAMP GENERATED ALWAYS AS (CREATED + INTERVAL '1 MINUTE') STORED
);