-- Function
CREATE
OR REPLACE FUNCTION DELETE_EXPIRED_SESSIONS () RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM SESSIONS WHERE EXPIRES < NOW();
    RETURN NULL;
END;
$$ LANGUAGE PLPGSQL;

-- Trigger
CREATE TRIGGER SESSIONS_TRIGGER_CLEANUP
AFTER INSERT
OR
UPDATE ON SESSIONS FOR EACH STATEMENT
EXECUTE FUNCTION DELETE_EXPIRED_SESSIONS ();