-- Function
CREATE
OR REPLACE FUNCTION UPDATE_TIMESTAMP () RETURNS TRIGGER AS $$
BEGIN
  NEW.updated = NOW();
  RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

-- Trigger
CREATE TRIGGER USERS_TRIGGER_UPDATE BEFORE
UPDATE ON USERS FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*)
EXECUTE FUNCTION UPDATE_TIMESTAMP ();